### PR TITLE
Port to 8.15

### PR DESCRIPTION
**Pull request by ppedrot**
This is a cleanup that makes this contribution compile with 8.15.

### CODE REVIEW

**Comment by palmskog** [comment]
Hi @ppedrot we appreciate that contribs are still receiving updates, but unless this is guaranteed one-time occurrence, maybe it would be an option to move the contrib to coq-community for better advertising and easier maintenance and automation? The basic requirement is that you volunteer to be the initial maintainer, but you can step down anytime.

**Comment by ppedrot** [comment]
I volunteered for this patch and stepped down immediately...

**Comment by palmskog** [comment]
@ppedrot then, if you are feeling done with this, please merge the PR.

**Comment by ppedrot** [comment]
I might push a few additional cleanups, but for the time being it doesn't hurt merging.

**Pull request merged**
